### ISSUE TITLE
[Feature] Drawings visible for Authors and GMs not matter the layer

### ISSUE THREAD

**Issue by Syrious** [dev7355608/advanced-drawing-tools#17]
Hey there!

First off, I just want to say that I’m absolutely loving this module! I have a feature request that I think could add even more value: I'd love to be able to make drawings on the canvas that are visible only to the GM, without needing to have the drawing layer active.

It would be super helpful for me as a GM to be able to sketch out movement plans or strategies for the NPCs — like showing how Goblin 2 plans to sneak into a room, while Bugbear 5 patrols a specific route.

Currently, switching to the drawing layer for this is a bit cumbersome, and it's easy to miss or forget something in the heat of the moment.

And on that note: It would also be awesome to start drawing in "invisible mode", so players won't see what I am planning 😈

Thanks a ton for all the work you’ve put into this module!

Best,
Syrious

**Comment by dev7355608** [comment]
This module is in maintenance only. I currently don't plan to add new features, because I don't have the time.

There's the [Quickdraw](https://foundryvtt.com/packages/quickdraw) module, which might allow you to do what you're asking. I haven't used this module. It's not a free module though and I'm not aware of a free alternative.

Maybe there's a module out there that allows you to quickly switch layers via a keybinding. There's also the option to write a macro that switches between the two layers.
