### ISSUE TITLE
cut section from drawing

### ISSUE THREAD

**Issue by Psychotopia** [dev7355608/advanced-drawing-tools#7]
is it possible to add a feature which allows you to create secondary internal borders, or failing that slice a drawinging in two so the edges of the slice can be worked?
![image](https://user-images.githubusercontent.com/75271642/206822562-1ee386ae-7b65-441a-bd9e-2540df5817a1.png)

**Comment by dev7355608** [comment]
Technically possible of course, but the problem is that the holes would vanish if the module is disabled. Also other modules working with the shape of the drawings wouldn't know of the holes, because technically the shape can only be polygon, circle/ellipse, rectangle (a pixi.js shape); so this might cause problems too. Initially I experimented with this idea, but I decided against it for those reasons and the fact that I would need override a lot making a bigger mess.
